version: '3'

services:
  debian:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: debian
    tty: true
    stdin_open: true
    volumes:
      - ./03-frontend/angular-ecommerce:/app/front
      - ./02-backend/spring-boot-ecommerce:/app/back
    ports:
      - 4200:4200
      - 5000:5000
    networks:
      - my-network

  mysql:
    image: mysql:latest
    container_name: dadabase
    environment:
      MYSQL_ROOT_PASSWORD: root_secure_password
      MYSQL_DATABASE: full-stack-ecommerce
      MYSQL_USER: appuser
      MYSQL_PASSWORD: secure_password
    ports:
      - 3306:3306
    networks:
      - my-network

networks:
  my-network: