version: '3'

services:
  debian:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: debian
    tty: true
    stdin_open: true
    volumes:
      - ./03-frontend/angular-ecommerce:/root/front
      - ./02-backend/spring-boot-ecommerce:/root/back
    ports:
      - 4200:4200
    networks:
      - my-network

  mysql:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: full-stack-ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
    networks:
      - my-network

networks:
  my-network: